"""add pipeline tables

Revision ID: 80f0c56ad0ef
Revises: 
Create Date: 2026-02-06 12:59:59.859912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f0c56ad0ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('output_files', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_jobs_status'), 'pipeline_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_jobs_step_name'), 'pipeline_jobs', ['step_name'], unique=False)
    op.create_table('pipeline_state',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_state')
    op.drop_index(op.f('ix_pipeline_jobs_step_name'), table_name='pipeline_jobs')
    op.drop_index(op.f('ix_pipeline_jobs_status'), table_name='pipeline_jobs')
    op.drop_table('pipeline_jobs')
    
    # SQLite does not support ENUM types natively or DROP TYPE.
    # Safe guard by checking dialect or catching the specific error.
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.execute('DROP TYPE jobstatus')
    # ### end Alembic commands ###
